def get_site_code(key):
    domain_vs_site_code = {"ef": "ef",
                           "mt": "mt",
                           "sdsp": "wt",
                           "sdz": "wv",
                           "owo": "wd",
                           "totr": "tt",
                           "llfl": "lf",
                           "at": "at",
                           "tp": "tp",
                           "dm": "dm",
                           "bp": "bp",
                           "llny": "nw",
                           "llca": "lc",
                           "ww": "ww",
                           "ub": "ub",
                           "ll": "ll",
                           "ch": "ch",
                           "hp": "hp",
                           "ba": "ba",
                           "lb": "lb",
                           "lg": "lg",
                           "dl": "lg",
                           "la": "la",
                           "lv": "lv",
                           "aq": "aq",
                           "ps": "ps",
                           "pp": "pp",
                           "wb": "wb",
                           "ht": "ht",
                           "fo": "fo",
                           "wa": "wa",
                           "lm": "lm",
                           "af": "af",
                           "ty": "ty",
                           "bv": "bv",
                           "rt": "rt",
                           "uc": "uc",
                           "ud": "ud",
                           "av": "av"}
    print(domain_vs_site_code[key])
    return domain_vs_site_code[key]


def get_attraction_code(key):
    attraction_vs_domain = {"ef": "br",
                            "llfl": "cc",
                            "tt": "gs",
                            "dm": "ap",
                            "mt": "ew",
                            "av": "xt",
                            "tp": "st",
                            "ty": "br"
                            }
    print(attraction_vs_domain[key])
    return attraction_vs_domain[key]


def get_time_zone(key):
    time_zone = {"ef": "Europe/Amsterdam",
                 "mt": "Europe/London",
                 "sdsp": "US/Pacific",
                 "sdz": "US/Pacific",
                 "owo": "US/Eastern",
                 "totr": "US/Eastern",
                 "llfl": "US/Eastern",
                 'av': "US/Eastern",
                 "at": "Europe/London",
                 "tp": "Europe/London",
                 "dm": "Europe/London",
                 "bp": "Europe/London",
                 "llny": "US/Eastern",
                 "llca": "US/Pacific",
                 "ww": "America/Sao_Paulo",
                 "ub": "Europe/London",
                 "ll": "Europe/London",
                 "ch": "Europe/London",
                 "hp": "Europe/Belgrade",
                 "ba": "Europe/London",
                 "lb": "Europe/Belgrade",
                 "lg": "Europe/Belgrade",
                 "dl": "Europe/London",
                 "la": "Europe/London",
                 "lv": "Europe/London",
                 "aq": "Europe/London",
                 "ps": "CET",
                 "pp": "Europe/London",
                 "wb": "US/Pacific",
                 "ht": "Europe/London",
                 "fo": "Europe/London",
                 "wa": "Israel",
                 "lm": "Europe/London",
                 "af": "US/Eastern",
                 "ty": "Asia/Tokyo",
                 "rt": "US/Eastern",
                 "uc": "Europe/London",
                 "ud": "Europe/London"}
    return time_zone[key]


def get_region_code(key):
    region_code = {"ef": "Europe/Amsterdam",
                   "mt": "uk",
                   "sdsp": "us",
                   "sdz": "us",
                   "owo": "us",
                   "totr": "us",
                   "llfl": "us",
                   'av': "us",
                   "at": "uk",
                   "tp": "uk",
                   "dm": "uk",
                   "bp": "uk",
                   "llny": "us",
                   "llca": "us",
                   "ww": "us",
                   "ub": "uk",
                   "ll": "uk",
                   "ch": "uk",
                   "hp": "uk",
                   "ba": "uk",
                   "lb": "uk",
                   "lg": "uk",
                   "dl": "uk",
                   "la": "uk",
                   "lv": "uk",
                   "aq": "uk",
                   "ps": "uk",
                   "pp": "uk",
                   "wb": "us",
                   "ht": "uk",
                   "fo": "uk",
                   "wa": "uk",
                   "lm": "uk",
                   "af": "us",
                   "ty": "ap",
                   "rt": "us",
                   "uc": "uk",
                   "ud": "uk"}
    return region_code[key]

def get_uuid_status(key):
    uuid_assignment = {"jpg_pairs": "jpg_pairs",
                       "all_files_same_uuid": "all_files_same_uuid",
                       "pre_association_in_meta_data": "pre_association_in_meta_data",
                       "origin_uuid_in_meta_data": "origin_uuid_in_meta_data"}
    return uuid_assignment[key]
